#!/bin/sh

# SSH
. ~/.sshalias

# GIT 
#alias git=hub
alias go='git checkout'
alias ga='git add'
alias gd='git diff'
alias gdc='git dc'

# Editer un fichier en graphique
alias edit="sublime"
alias s="sublime"
alias sublim="sublime"

# Système
alias updatedb="sudo /usr/libexec/locate.updatedb"
alias "alias-reload"='. ~/.alias'
alias "rm-eclipse-files"='find . \( -name ".DS_Store" -or -name ".classpath" -or -name ".project" -or -name ".scala_dependencies" -or -name ".settings" -or -name ".cache" \) | xargs rm -r '

# Postgresql
#alias "pg-log"="tail -f /usr/local/var/postgres/pg_log/$(ls -t /usr/local/var/postgres/pg_log/ | cut -f1 | head -n 1)"
alias "pg-start"="sudo -u postgres pg_ctl -D /Library/PostgreSQL/8.4/data -l /var/log/pg/logfile start"
alias "pg-stop"="sudo -u postgres pg_ctl -D /Library/PostgreSQL/8.4/data stop"

# Mysql
alias "mysql-start"="mysql.server start"
alias "mysql-stop"="mysql.server stop"

# Play
alias "play21"="~/Travail/outils/play20-master/play"
alias "play21-rc2"="~/Travail/outils/play-2.1-rc2/play"

guillemet="\""
pvmauto() { 
	pvm use $(cat project/plugins.sbt | grep sbt-plugin | cut -d $guillemet -f 6) && play; 
}

# ANT COLOR
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
ant () { command ant  -logger org.apache.tools.ant.listener.AnsiColorLogger "$@" | sed 's/2;//g' ; }

alias "json"="python -mjson.tool"

alias "dropdb nrsu; createdb -O nrsu nrsu"

alias es="elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml"
