#!/bin/bash

basedir=`pwd`
destdir="/media/Stockage/Divx"

if [[ -z "$1" ]]; then
 echo "IN file required"
 exit
fi

if [[ -z "$2" ]]; then
  echo "OUT filename required"
  exit
fi

if [[ -z "$3" ]]; then
  echo "OUT year required"
  exit
fi

if [[ -z "$4" ]]; then
  tag=""
else
  tag="[$4]"
fi

file=$1
in="$basedir/$file"

filename=$2
year=$3

# get extension
realfilename=$(basename "$file")
extension="${realfilename##*.}"

# construct filename
finalname="$filename ($year) $tag.$extension"
out="$destdir/$finalname"

echo "Copying to $out"
rsync -Pa "$in" "$out" && rm "$in"

exit 1
